### ISSUE TITLE
Add more stacks in integration tests to compare latency respect to other resolution engines

### ISSUE THREAD

**Issue by pacospace** [thoth-station/integration-tests#165]
**Is your feature request related to a problem? Please describe.**
As Thoth Developer,

I want to verify the latency for obtaining stacks recommended by thoth to be sure users can receive answers in time.
These results can be compared with other resolution engines (e.g. pipenv)

**Describe the solution you'd like**
Add them to https://github.com/thoth-station/integration-tests/tree/master/features/data/project

**Describe alternatives you've considered**

**Additional context**
![Screenshot from 2021-03-19 15-27-11](https://user-images.githubusercontent.com/27498679/111795627-ac913900-88c7-11eb-95c0-062feb8f9ffa.png)

The selection of stacks can be obtained from data stored in thoth knowledge graph.

**Comment by pacospace** [comment]
- [ ] Create a notebook analyzing adviser reports considering properties of an advise respect to time respect to software stack size
- [ ] Create new integration test for stack that need to be monitored based on  adivser users (Data Driven Engineering)

**Comment by pacospace** [comment]
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi-org"

[packages]
pandas = "*"

[dev-packages]

[requires]
python_version = "3.8"

TLS verification turned off, its highly recommended to use a secured connection, see configuration file for configuration options

response obtained in s 661.6509959370014 -> 11 min??
```

cc @fridex @harshad16 @goern

**Comment by harshad16** [comment]
we can started with increasing the resource for adviser and then check in the pipeline which component is taking the most time after adviser.
The general recommendation pipeline steps are: `user-request->user-api->kafka->investigator-consumer->adviser-workflow`

**Comment by pacospace** [comment]
> we can start with increasing the resource for adviser and then check in the pipeline which component is taking the most time after adviser.
> The general recommendation pipeline steps are: `user-request->user-api->kafka->investigator-consumer->adviser-workflow`

from adviser logs:
```
{"name": "thoth.adviser.resolver", "levelname": "INFO", "module": "resolver", "lineno": 1257, "funcname": "_do_resolve_states", "created": 1616441903.0006084, "asctime": "2021-03-22 19:38:23,000", "msecs": 0.6084442138671875, "relative_created": 645426.8260002136, "process": 56, "message": "Resolver took 642.466 seconds in total, pipeline speed 0.0015565 stacks/second"}
```

**Comment by pacospace** [comment]
This time response obtained in s 573.9063466049993 -> less then 10 minutes

**Comment by pacospace** [comment]
> This time response obtained in s 573.9063466049993 -> less then 10 minutes (adviser-210322204745-a57da36e1d819a6c) using new changes after https://github.com/thoth-station/thoth-application/pull/1092

**Comment by fridex** [comment]
Note the design of adviser - it is not resolver as Pipenv or others. It resolves multiple lock files (stacks), evaluates their score, and learns from that. Certain CPU time is allocated for this process to work - see docs for more info:

https://thoth-station.ninja/docs/developers/adviser/deployment.html#allocating-cpu-time 

Currently we give 15 minutes adviser to finish based on the configuration:

https://github.com/thoth-station/thoth-application/blob/1762ae1f9d97d13385720b1108d6aca2a39eda9b/adviser/base/argo-workflows/advise.yaml#L208

It can terminate if:

- no stacks are found or unsolved dependencies are present in the stack
- no more graph traversals left (I guess that's the case for pandas, resolver's log will give more insights)
- CPU time is exhausted and the resolver terminates after 15 minutes (current value)

**Comment by pacospace** [comment]
> Note the design of adviser - it is not resolver as Pipenv or others. It resolves multiple lock files (stacks), evaluates their score, and learns from that. Certain CPU time is allocated for this process to work - see docs for more info:
> 
> https://thoth-station.ninja/docs/developers/adviser/deployment.html#allocating-cpu-time
> 
> Currently we give 15 minutes adviser to finish based on the configuration:
> 
> https://github.com/thoth-station/thoth-application/blob/1762ae1f9d97d13385720b1108d6aca2a39eda9b/adviser/base/argo-workflows/advise.yaml#L208
> 
> It can terminate if:
> 
> * no stacks are found or unsolved dependencies are present in the stack
> * no more graph traversals left (I guess that's the case for pandas, resolver's log will give more insights)
> * CPU time is exhausted and the resolver terminates after 15 minutes (current value)

why for thamos we have more than double for timeout? https://github.com/thoth-station/thamos/blob/dd50f2a2ba76a3257220ae665614108c07c84c50/thamos/lib.py#L75

**Comment by fridex** [comment]
> why for thamos we have more than double for timeout? https://github.com/thoth-station/thamos/blob/dd50f2a2ba76a3257220ae665614108c07c84c50/thamos/lib.py#L75

As the request for users are queued and it requires some time for the request to be processed. The timeout also considers non-empty namespace when we need to serve other users first (first come first served).
