### ISSUE TITLE
print versions under test to test report

### ISSUE THREAD

**Issue by goern** [thoth-station/integration-tests#171]
**Is your feature request related to a problem? Please describe.**
As a Thoth DevOps,
I want to see an integration test report,
so that I can easily read the versions of API under test

**Describe the solution you'd like**
just add to the report, HTML and text

**Describe alternatives you've considered**
n/a

**Additional context**
This shall be the input to the release planning meeting.

/kind feature
/sig devops

**Comment by fridex** [comment]
Depends-On: https://github.com/thoth-station/thoth-application/issues/609
