### ISSUE TITLE
Include test for executing thamos advise on opencv containing software stack

### ISSUE THREAD

**Issue by harshad16** [thoth-station/integration-tests#175]
**Is your feature request related to a problem? Please describe.**
- It would be great if we include a test that executes thamos advise on a OpenCV containing software stack. 
Chat thread link: https://chat.google.com/room/AAAA9x27brI/jECRY0jGUrU

**High-level Goals**
list of high-level Acceptance Criteria/Goals (that is signed off by the team, and unchangeable)
- High availability of the advice, as it would have been significantly queried by the integration tests.

**Describe the solution you'd like**
include a feature to the behave with this.

**Describe alternatives you've considered**
none

**Additional context**
Included the link of the chat above.

**Acceptance Criteria**
checklist of detailed Acceptance Criteria (that might extend over the lifetime of the card)

[] include a new feature to behave
[] make sure the prod service is able to full fil the request.

**Comment by pacospace** [comment]
we added integration test for predictive stack with computer vision that have opencv, should we consider this done? https://github.com/thoth-station/integration-tests/pull/206/files

**Comment by pacospace** [comment]
> we added integration test for predictive stack with computer vision that have opencv, should we consider this done? https://github.com/thoth-station/integration-tests/pull/206/files

Cc @harshad16 we can close this I think ;)
