### ISSUE TITLE
Create integrations tests for SI [13pt]

### ISSUE THREAD

**Issue by goern** [thoth-station/integration-tests#20]
- si workflow on new package_version
- without adviser
- using adviser with recommendation type security

**Comment by goern** [comment]
@bissenbay any progress on this?

**Comment by fridex** [comment]
I think we can close this. We have unit tests for security indicators that verify their correctness on the adviser level. Then we have integration tests that verify the correctness of adviser in a deployment.

/close

**Comment by fridex** [comment]
Oh, now I see it was related to a new package release.

**Comment by fridex** [comment]
Add a note to internal trigger tests that should verify this: https://github.com/thoth-station/integration-tests/issues/70
