### ISSUE TITLE
Some integration tests are getting old

### ISSUE THREAD

**Issue by fridex** [thoth-station/integration-tests#225]
**Describe the bug**

It would be great to respect new API endpoints and make changes to respect the current implementation.

**To Reproduce**
1. See the current integration test results.

**Expected behavior**

Integration tests should be green.

**Additional context**

See for example tests involving metadata - they still use old metadata endpoint. Also, tests assume tensorflow==2.0.0 which is getting old. Worth updating tests to query more recent package versions.

**Comment by codificat** [comment]
Tests to improve:
- [ ] compare endpoints from the user-api with the current integration tests
- [ ] create issues for the enpoints that are outdated or missing

New Tests to add:
- [ ] kebechet: see thoth-station/kebechet#972
- [ ] search: create a separate issue.  search -> API  (there are unit tests covering advisor references to search)

Coverage will be reviewed in a meeting

**Comment by Gkrumbach07** [comment]
>  search: create a separate issue. search -> API (there are unit tests covering advisor references to search)

https://github.com/thoth-station/search/issues/49

**Comment by fridex** [comment]
Let's see if we can incorporate also https://github.com/thoth-station/user-api/issues/1353 into some tests that could be run from time to time (maybe not daily but to make sure there are no perf regression - ex. db response in a reasonable time with indexes configured).

**Comment by harshad16** [comment]
The integration test seems to be functioning all green now in stage cluster.
closing the issue.
