### ISSUE TITLE
Run integration-tests in parallel

### ISSUE THREAD

**Issue by fridex** [thoth-station/integration-tests#275]
**Is your feature request related to a problem? Please describe.**

As of now, it takes more than 4 hours for integration-tests to finish. We should experiment running behave features in parallel.

**Comment by mayaCostantini** [comment]
After research, we concluded that this will not be possible to implement unless if we want to stop using behave for testing, because there does not seem to be any stable or recent `behave-parallel` package available. Closing this issue.
/close
