### ISSUE TITLE
Integration tests fail for dependency monkey in ocp4-stage

### ISSUE THREAD

**Issue by fridex** [thoth-station/integration-tests#316]
**Describe the bug**

See one of the recent integration-tests reports:
```
Assertion Failed: Bad HTTP status code received when scheduling Dependency Monkey (400): {
  "detail": "'requirements_locked' is a required property",
  "status": 400,
  "title": "Bad Request",
  "type": "about:blank"
}
```

**Expected behavior**

Dependency monkey integration tests should be green.

**Additional context**

This looks like an issue related to recent adjustments to the API schema.

**Comment by mayaCostantini** [comment]
The logs from the `management-api-1386-vktlp` in stage indicate that the version of `management-api` used is still `v0.18.2` whereas the change in the schema was introduced in [`v0.18.3`](https://github.com/thoth-station/management-api/pull/881#issue-1195906834):

```
2022-04-07 12:05:21,319  24 INFO     thoth.management_api:58: This is Management API v0.18.2+storage.0.71.1.common.0.36.1
```

**Comment by mayaCostantini** [comment]
Closing this issue as it seems to be solved as it was caused by management API version not being up to date. I also tested the dependency-monkey integration tests locally against the stage cluster and they were all green.
