### ISSUE TITLE
validate that test and stage provide TLS endpoints

### ISSUE THREAD

**Issue by goern** [thoth-station/integration-tests#33]
validate that 
- [ ] user, management, amun api in test, stage provide HTTPS
- [ ] test.sh is configured for HTTPS

**Comment by harshad16** [comment]
These routes are available in openshift ocp cluster with latest certs 
https://amun.test.thoth-station.ninja/api/v1/ui
https://amun.stage.thoth-station.ninja/api/v1/ui

however, it feels like we need to check the route53 configuration.

**Comment by bissenbay** [comment]
> These routes are available in openshift ocp cluster with latest certs
> https://amun.test.thoth-station.ninja/api/v1/ui
> https://amun.stage.thoth-station.ninja/api/v1/ui
> 
> however, it feels like we need to check the route53 configuration.

For me, it says: `Application is not available`.
The application is currently not serving requests at this endpoint. It may not have been started or is still starting.

**Comment by goern** [comment]
is this fixed?

**Comment by bissenbay** [comment]
> is this fixed?

If you just follow those links they don't work, but if you prepend `https://` then they work.

**Comment by bissenbay** [comment]
@goern 
For me, all the following endpoints work, so I think we can tick the first task:
1. https://test.thoth-station.ninja/api/v1/ui/
2. https://management.test.thoth-station.ninja/api/v1/ui/
3. https://amun.test.thoth-station.ninja/api/v1/ui/
4. https://stage.thoth-station.ninja/api/v1/ui/
5. https://management.stage.thoth-station.ninja/api/v1/ui/
6. https://amun.stage.thoth-station.ninja/api/v1/ui/
