### ISSUE TITLE
Need a test for `thamos images`

### ISSUE THREAD

**Issue by codificat** [thoth-station/integration-tests#348]
`thamos images` stopped working correctly after a change in user-api (https://github.com/thoth-station/thamos/issues/1184) and this is not captured by current integration tests.

The current integration tests include [containe images API](https://github.com/thoth-station/integration-tests/blob/master/features/container_images.feature) coverage but not from `thamos`.

**Comment by VannTen** [comment]
Could'nt we have a automatic PR generating the thamos openapi client when the relevant user-api is updated, and let the usual ci (mypy in particular for catching bad usages) point us to fixes ?

**Comment by codificat** [comment]
> Could'nt we have an automatic PR generating the thamos openapi client when the relevant user-api is updated

That would be nice to have, but we don't have anything similar available yet, right?

> and let the usual ci (mypy in particular for catching bad usages) point us to fixes ?

Would mypy catch this particular issue though? I think the problem in [the code involved](https://github.com/thoth-station/thamos/blob/4536f4d67e362107a2d40ceaef34901365148a1c/thamos/lib.py#L1316-L1329) in thoth-station/thamos#1184 is more semantic/logic than what mypy would catch, no?

**Comment by VannTen** [comment]
On Tue, Oct 11, 2022 at 04:14:45AM -0700, Pep Turró Mauri wrote:
> > and let the usual ci (mypy in particular for catching bad usages) point us to fixes ?
> 
> Would mypy catch this particular issue though? I think the problem in [the code involved](https://github.com/thoth-station/thamos/blob/4536f4d67e362107a2d40ceaef34901365148a1c/thamos/lib.py#L1316-L1329) in thoth-station/thamos#1184 is more semantic/logic than what mypy would catch, no?
> 

I don't know swapper-codegen enough, but in principle it's possible to
represent a 404 as Optionnal/Union/ that sort of things (maybe I'm a bit
optimistic on the general support of typing across the Python ecosystem
^).

Missing that, just opening a PR automatically would still be good:
during review, we would have the opportunity to spot unhandled API
responses, etc.

**Comment by goern** [comment]
do we turn this into a RFE (wrt openapi regeneration...) and close this because auf #351  ?

@VannTen @codificat

**Comment by VannTen** [comment]
It might be in a separate issue. I think a integration test for `thamos images` is easier than automatic openapi regeneration, and it can probably catch other things.

**Comment by Gkrumbach07** [comment]
Closing as parent [issue](https://github.com/thoth-station/thamos/issues/1184) is resolved and these test will no longer be relevant. As long as `/container-images` is tested, then this thamos command will be covered as well because the parent issue removed any additional logic that was applied after the api call.

/close
