### ISSUE TITLE
"Scenario: Querying for Python package versions solved" failes

### ISSUE THREAD

**Issue by goern** [thoth-station/integration-tests#35]
```
Feature: Querying Thoth for Python package versions solved for all solvers # features/package_versions_solved.feature:1

  Scenario: Querying for Python package versions solved                                          # features/package_versions_solved.feature:3
    Given a list of packages                                                                     # features/steps/python_package_solved.py:29 0.000s
      | package_name |
      | setuptools   |
    And number of versions for each package_name is available                                    # features/steps/python_package_solved.py:37 0.327s
    And deployment is accessible using HTTPS                                                     # features/steps/basic.py:31 1.190s
    And number of solvers available is provided                                                  # features/steps/python_package_solved.py:47 0.846s
      Traceback (most recent call last):
        File "/home/goern/.local/share/virtualenvs/integration-tests-Me6nOCO7/lib/python3.6/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/home/goern/.local/share/virtualenvs/integration-tests-Me6nOCO7/lib/python3.6/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/python_package_solved.py", line 52, in step_impl
          available_solvers = [str(solver["solver_name"]) for solver in data["solvers"]["python"]]
      KeyError: 'solvers'

    When I query for the solved packages for the package_name from PyPI in Thoth Knowledge Graph # None
    Then I should get the same number provided from PyPI                                         # None
```

**Comment by bissenbay** [comment]
If we request https://management.stage.thoth-station.ninja/api/v1/solvers `stage` env, then it works good, but if we request`test` env https://management.test.thoth-station.ninja/api/v1/solvers, then fails. Looks some problem in how `usera-api` for test is deployment. @fridex

**Comment by goern** [comment]
what is the problem? any logs?

**Comment by bissenbay** [comment]
> what is the problem? any logs?

```
2020-09-02 02:13:35,131  27 ERROR    thoth.management_api.openapi_server:1892: Exception on /api/v1/solvers [GET]
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/app-root/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/uri_parsing.py", line 144, in wrapper
    response = function(request)
  File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/parameter.py", line 121, in wrapper
    return function(**kwargs)
  File "/opt/app-root/src/thoth/management_api/api_v1.py", line 184, in list_solvers
    solver_info = GraphDatabase.parse_python_solver_name(solver_name)
AttributeError: type object 'GraphDatabase' has no attribute 'parse_python_solver_name'
```
So, looks like `management-api` is running from this image https://quay.io/repository/thoth-station/management-api/manifest/sha256:5c222b4f30b2deaef16087774dcf127f70310718995ad440dd6d87345e024d4c which is old, so should I update to the latest?

**Comment by fridex** [comment]
> > what is the problem? any logs?
> 
> ```
> 2020-09-02 02:13:35,131  27 ERROR    thoth.management_api.openapi_server:1892: Exception on /api/v1/solvers [GET]
> Traceback (most recent call last):
>   File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/opt/app-root/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
>     raise value
>   File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
>     response = function(request)
>   File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/uri_parsing.py", line 144, in wrapper
>     response = function(request)
>   File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/parameter.py", line 121, in wrapper
>     return function(**kwargs)
>   File "/opt/app-root/src/thoth/management_api/api_v1.py", line 184, in list_solvers
>     solver_info = GraphDatabase.parse_python_solver_name(solver_name)
> AttributeError: type object 'GraphDatabase' has no attribute 'parse_python_solver_name'
> ```
> 
> So, looks like `management-api` is running from this image https://quay.io/repository/thoth-station/management-api/manifest/sha256:5c222b4f30b2deaef16087774dcf127f70310718995ad440dd6d87345e024d4c which is old, so should I update to the latest?

This should be already fixed with recent versions of management-api. I guess a rollout needs to be triggered for the test environment?

**Comment by fridex** [comment]
> I guess a rollout needs to be triggered for the test environment?

Triggered, test is running the most recent user-api/management-api.

**Comment by bissenbay** [comment]
> Triggered, test is running the most recent user-api/management-api.
Thanks, this can be closed, as https://management.test.thoth-station.ninja/api/v1/solvers working now.
