### ISSUE TITLE
"Scenario: Run a simple thamos advise for a flask application for raw HTTP connection" fails

### ISSUE THREAD

**Issue by goern** [thoth-station/integration-tests#36]
```
  Scenario: Run a simple thamos advise for a flask application for raw HTTP connection     # features/thamos_advise.feature:3
    Given deployment is accessible using HTTPS                                             # features/steps/basic.py:31 1.146s
    When thamos advise is run for flask_py36 for recommendation type LATEST asynchronously # features/steps/basic.py:58 1.192s
      Traceback (most recent call last):
        File "/home/goern/.local/share/virtualenvs/integration-tests-Me6nOCO7/lib/python3.6/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/home/goern/.local/share/virtualenvs/integration-tests-Me6nOCO7/lib/python3.6/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/basic.py", line 85, in thamos_advise
          debug=True,
        File "/home/goern/.local/share/virtualenvs/integration-tests-Me6nOCO7/lib/python3.6/site-packages/thamos/lib.py", line 89, in wrapper
          result = func(api_client, *args, **kwargs)
        File "/home/goern/.local/share/virtualenvs/integration-tests-Me6nOCO7/lib/python3.6/site-packages/thamos/lib.py", line 367, in advise
          response = api_instance.post_advise_python(advise_input, **parameters)
        File "/home/goern/.local/share/virtualenvs/integration-tests-Me6nOCO7/lib/python3.6/site-packages/thamos/swagger_client/thoth/advise_api.py", line 434, in post_advise_python
          (data) = self.post_advise_python_with_http_info(body, recommendation_type, **kwargs)  # noqa: E501
        File "/home/goern/.local/share/virtualenvs/integration-tests-Me6nOCO7/lib/python3.6/site-packages/thamos/swagger_client/thoth/advise_api.py", line 554, in post_advise_python_with_http_info
          collection_formats=collection_formats)
        File "/home/goern/.local/share/virtualenvs/integration-tests-Me6nOCO7/lib/python3.6/site-packages/thamos/swagger_client/api_client.py", line 321, in call_api
          _preload_content, _request_timeout)
        File "/home/goern/.local/share/virtualenvs/integration-tests-Me6nOCO7/lib/python3.6/site-packages/thamos/swagger_client/api_client.py", line 152, in __call_api
          _request_timeout=_request_timeout)
        File "/home/goern/.local/share/virtualenvs/integration-tests-Me6nOCO7/lib/python3.6/site-packages/thamos/swagger_client/api_client.py", line 364, in request
          body=body)
        File "/home/goern/.local/share/virtualenvs/integration-tests-Me6nOCO7/lib/python3.6/site-packages/thamos/swagger_client/rest.py", line 274, in POST
          body=body)
        File "/home/goern/.local/share/virtualenvs/integration-tests-Me6nOCO7/lib/python3.6/site-packages/thamos/swagger_client/rest.py", line 227, in request
          raise ApiException(http_resp=r)
      thamos.swagger_client.rest.ApiException: (400)
      Reason: BAD REQUEST
      HTTP response headers: HTTPHeaderDict({'Server': 'gunicorn/20.0.4', 'Date': 'Tue, 25 Aug 2020 07:17:03 GMT', 'Content-Type': 'application/problem+json', 'Content-Length': '136', 'Access-Control-Allow-Origin': '*', 'X-Thoth-Version': '0.6.9', 'Set-Cookie': '99ca826347b0162a0aa474189c69e824=a27b82616b37342ceb8a8082ff754911; path=/; HttpOnly; Secure'})
      HTTP response body: {
        "detail": "Extra query parameter(s) limit_latest_versions not in spec",
        "status": 400,
        "title": null,
        "type": "about:blank"
      }
      
      
      
      Captured logging:
      WARNING:thamos.config:TLS verification turned off, its highly recommended to use a secured connection, see configuration file for configuration options

    Then wait for adviser to finish successfully                                           # None
    Then I should be able to retrieve adviser results                                      # None
    Then adviser result has pinned down software stack with report                         # None
```

**Comment by fridex** [comment]
> ```
>         "detail": "Extra query parameter(s) limit_latest_versions not in spec",
> ```

We no longer support `limit_latest_versions`. It looks like `thamos` is too old.

**Comment by fridex** [comment]
Related: https://github.com/thoth-station/integration-tests/pull/37#issue-473135691

**Comment by bissenbay** [comment]
@fridex I did remove `limit_latest_versions` on line https://github.com/thoth-station/integration-tests/blob/master/features/steps/basic.py#L80 and still getting the error:
```
Feature: Running thamos advise against deployment # features/thamos_advise.feature:1

  Scenario: Run a simple thamos advise for a flask application for raw HTTP connection     # features/thamos_advise.feature:3
    Given deployment is accessible using HTTPS                                             # features/steps/basic.py:31 0.392s
    When thamos advise is run for flask_py36 for recommendation type LATEST asynchronously # features/steps/basic.py:58 0.605s
      Traceback (most recent call last):
        File "/home/bdauletb/.local/share/virtualenvs/integration-tests-PN0lkqBU/lib/python3.6/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/home/bdauletb/.local/share/virtualenvs/integration-tests-PN0lkqBU/lib/python3.6/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/basic.py", line 84, in thamos_advise
          debug=True,
        File "/home/bdauletb/.local/share/virtualenvs/integration-tests-PN0lkqBU/lib/python3.6/site-packages/thamos/lib.py", line 98, in wrapper
          result = func(api_client, *args, **kwargs)
        File "/home/bdauletb/.local/share/virtualenvs/integration-tests-PN0lkqBU/lib/python3.6/site-packages/thamos/lib.py", line 400, in advise
          response = api_instance.post_advise_python(advise_input, **parameters)
        File "/home/bdauletb/.local/share/virtualenvs/integration-tests-PN0lkqBU/lib/python3.6/site-packages/thamos/swagger_client/thoth/advise_api.py", line 465, in post_advise_python
          body, recommendation_type, **kwargs
        File "/home/bdauletb/.local/share/virtualenvs/integration-tests-PN0lkqBU/lib/python3.6/site-packages/thamos/swagger_client/thoth/advise_api.py", line 616, in post_advise_python_with_http_info
          collection_formats=collection_formats,
        File "/home/bdauletb/.local/share/virtualenvs/integration-tests-PN0lkqBU/lib/python3.6/site-packages/thamos/swagger_client/api_client.py", line 357, in call_api
          _request_timeout,
        File "/home/bdauletb/.local/share/virtualenvs/integration-tests-PN0lkqBU/lib/python3.6/site-packages/thamos/swagger_client/api_client.py", line 165, in __call_api
          _request_timeout=_request_timeout,
        File "/home/bdauletb/.local/share/virtualenvs/integration-tests-PN0lkqBU/lib/python3.6/site-packages/thamos/swagger_client/api_client.py", line 427, in request
          body=body,
        File "/home/bdauletb/.local/share/virtualenvs/integration-tests-PN0lkqBU/lib/python3.6/site-packages/thamos/swagger_client/rest.py", line 346, in POST
          body=body,
        File "/home/bdauletb/.local/share/virtualenvs/integration-tests-PN0lkqBU/lib/python3.6/site-packages/thamos/swagger_client/rest.py", line 250, in request
          raise ApiException(http_resp=r)
      thamos.swagger_client.rest.ApiException: (500)
      Reason: INTERNAL SERVER ERROR
      HTTP response headers: HTTPHeaderDict({'Server': 'gunicorn/20.0.4', 'Date': 'Tue, 25 Aug 2020 15:04:54 GMT', 'Content-Type': 'application/json', 'Content-Length': '177', 'X-Thoth-Version': '0.6.9', 'Access-Control-Allow-Origin': '*', 'Set-Cookie': '99ca826347b0162a0aa474189c69e824=a27b82616b37342ceb8a8082ff754911; path=/; HttpOnly; Secure'})
      HTTP response body: {"details":{"datetime":"2020-08-25T15:04:54.349567","type":"InternalServerError"},"error":"Internal server error occurred, please contact administrator with provided details."}
      
      
      
      Captured logging:
      WARNING:thamos.config:TLS verification turned off, its highly recommended to use a secured connection, see configuration file for configuration options

    Then wait for adviser to finish successfully                                           # None
    Then I should be able to retrieve adviser results                                      # None
    Then adviser result has pinned down software stack with report                         # None


Failing scenarios:
  features/db_status.feature:2  Estabilishing a connection to the Database
  features/package_metadata.feature:2  Querying for the known Python Package Indices
  features/package_versions_solved.feature:3  Querying for Python package versions solved
  features/solvers.feature:2  Check there are minimum solvers available in Thoth
  features/thamos_advise.feature:3  Run a simple thamos advise for a flask application for raw HTTP connection

2 features passed, 5 failed, 0 skipped
6 scenarios passed, 5 failed, 0 skipped
28 steps passed, 5 failed, 8 skipped, 0 undefined
Took 4m30.095s
```
But, this time it's not `BAD REQUEST`, but `INTERNAL SERVER ERROR`, it's this because of changes made in https://github.com/thoth-station/amun-client/pull/143?

**Comment by fridex** [comment]
> But, this time it's not `BAD REQUEST`, but `INTERNAL SERVER ERROR`, it's this because of changes made in [thoth-station/amun-client#143](https://github.com/thoth-station/amun-client/pull/143)?

I think the `limit_latest_version` issue went away with the amun-client update. My wild guess is that the issue you are experiencing is related to this one https://github.com/thoth-station/user-api/issues/1007 The workflow errored for some reason and API failed to produce reasonable error response which should be fixed in https://github.com/thoth-station/user-api/pull/1009 Now the question is why the workflow errored.

**Comment by fridex** [comment]
> Now the question is why the workflow errored.

Checking old workflows, many of them failed due to unsufficient resources. I'll try to experiment with new argo which should handle resources in a better way.

**Comment by fridex** [comment]
> > Now the question is why the workflow errored.
> 
> Checking old workflows, many of them failed due to unsufficient resources. I'll try to experiment with new argo which should handle resources in a better way.

Observations after few experiments:

adviser workflow was failing due to resources. Even though there were resources available on the workflow start, if there was a parallel kebechet workflow, it eated up resources needed for adviser workflow and hence adviser workflow failed. With old Argo workflow-controller v2.9.5, Argo was not able to recover from these resources issues. I installed community build of Argo https://github.com/argoproj/argo/issues/1913#issuecomment-678978461 which seems to be handling resources in a better way. Let's observe how this will work out.

Adviser workflow is now successfully started.

**Comment by bissenbay** [comment]
> @fridex I did remove `limit_latest_versions` on line https://github.com/thoth-station/integration-tests/blob/master/features/steps/basic.py#L80 and still getting the error:
> 
> ```
> Feature: Running thamos advise against deployment # features/thamos_advise.feature:1
> 
>   Scenario: Run a simple thamos advise for a flask application for raw HTTP connection     # features/thamos_advise.feature:3
>     Given deployment is accessible using HTTPS                                             # features/steps/basic.py:31 0.392s
>     When thamos advise is run for flask_py36 for recommendation type LATEST asynchronously # features/steps/basic.py:58 0.605s
>       Traceback (most recent call last):
>         File "/home/bdauletb/.local/share/virtualenvs/integration-tests-PN0lkqBU/lib/python3.6/site-packages/behave/model.py", line 1329, in run
>           match.run(runner.context)
>         File "/home/bdauletb/.local/share/virtualenvs/integration-tests-PN0lkqBU/lib/python3.6/site-packages/behave/matchers.py", line 98, in run
>           self.func(context, *args, **kwargs)
>         File "features/steps/basic.py", line 84, in thamos_advise
>           debug=True,
>         File "/home/bdauletb/.local/share/virtualenvs/integration-tests-PN0lkqBU/lib/python3.6/site-packages/thamos/lib.py", line 98, in wrapper
>           result = func(api_client, *args, **kwargs)
>         File "/home/bdauletb/.local/share/virtualenvs/integration-tests-PN0lkqBU/lib/python3.6/site-packages/thamos/lib.py", line 400, in advise
>           response = api_instance.post_advise_python(advise_input, **parameters)
>         File "/home/bdauletb/.local/share/virtualenvs/integration-tests-PN0lkqBU/lib/python3.6/site-packages/thamos/swagger_client/thoth/advise_api.py", line 465, in post_advise_python
>           body, recommendation_type, **kwargs
>         File "/home/bdauletb/.local/share/virtualenvs/integration-tests-PN0lkqBU/lib/python3.6/site-packages/thamos/swagger_client/thoth/advise_api.py", line 616, in post_advise_python_with_http_info
>           collection_formats=collection_formats,
>         File "/home/bdauletb/.local/share/virtualenvs/integration-tests-PN0lkqBU/lib/python3.6/site-packages/thamos/swagger_client/api_client.py", line 357, in call_api
>           _request_timeout,
>         File "/home/bdauletb/.local/share/virtualenvs/integration-tests-PN0lkqBU/lib/python3.6/site-packages/thamos/swagger_client/api_client.py", line 165, in __call_api
>           _request_timeout=_request_timeout,
>         File "/home/bdauletb/.local/share/virtualenvs/integration-tests-PN0lkqBU/lib/python3.6/site-packages/thamos/swagger_client/api_client.py", line 427, in request
>           body=body,
>         File "/home/bdauletb/.local/share/virtualenvs/integration-tests-PN0lkqBU/lib/python3.6/site-packages/thamos/swagger_client/rest.py", line 346, in POST
>           body=body,
>         File "/home/bdauletb/.local/share/virtualenvs/integration-tests-PN0lkqBU/lib/python3.6/site-packages/thamos/swagger_client/rest.py", line 250, in request
>           raise ApiException(http_resp=r)
>       thamos.swagger_client.rest.ApiException: (500)
>       Reason: INTERNAL SERVER ERROR
>       HTTP response headers: HTTPHeaderDict({'Server': 'gunicorn/20.0.4', 'Date': 'Tue, 25 Aug 2020 15:04:54 GMT', 'Content-Type': 'application/json', 'Content-Length': '177', 'X-Thoth-Version': '0.6.9', 'Access-Control-Allow-Origin': '*', 'Set-Cookie': '99ca826347b0162a0aa474189c69e824=a27b82616b37342ceb8a8082ff754911; path=/; HttpOnly; Secure'})
>       HTTP response body: {"details":{"datetime":"2020-08-25T15:04:54.349567","type":"InternalServerError"},"error":"Internal server error occurred, please contact administrator with provided details."}
>       
>       
>       
>       Captured logging:
>       WARNING:thamos.config:TLS verification turned off, its highly recommended to use a secured connection, see configuration file for configuration options
> 
>     Then wait for adviser to finish successfully                                           # None
>     Then I should be able to retrieve adviser results                                      # None
>     Then adviser result has pinned down software stack with report                         # None
> 
> 
> Failing scenarios:
>   features/db_status.feature:2  Estabilishing a connection to the Database
>   features/package_metadata.feature:2  Querying for the known Python Package Indices
>   features/package_versions_solved.feature:3  Querying for Python package versions solved
>   features/solvers.feature:2  Check there are minimum solvers available in Thoth
>   features/thamos_advise.feature:3  Run a simple thamos advise for a flask application for raw HTTP connection
> 
> 2 features passed, 5 failed, 0 skipped
> 6 scenarios passed, 5 failed, 0 skipped
> 28 steps passed, 5 failed, 8 skipped, 0 undefined
> Took 4m30.095s
> ```
> 
> But, this time it's not `BAD REQUEST`, but `INTERNAL SERVER ERROR`, it's this because of changes made in [thoth-station/amun-client#143](https://github.com/thoth-station/amun-client/pull/143)?

@fridex Do you want me to push PR where I removed `limit_latest_versions`?

**Comment by fridex** [comment]
> @fridex Do you want me to push PR where I removed `limit_latest_versions`?

Yes, please do so. It is no longer supported.

**Comment by goern** [comment]
fixed?

**Comment by goern** [comment]
what is the status of this?

**Comment by bissenbay** [comment]
It fails with error below:
```
Feature: Running thamos advise against deployment # features/thamos_advise.feature:1

  Scenario: Run a simple thamos advise for a flask application for raw HTTP connection     # features/thamos_advise.feature:3
    Given deployment is accessible using HTTPS                                             # features/steps/basic.py:31 0.383s
    When thamos advise is run for flask_py36 for recommendation type LATEST asynchronously # features/steps/basic.py:58 0.622s
    Then wait for adviser to finish successfully                                           # features/steps/basic.py:88 0.205s
      Traceback (most recent call last):
        File "/home/bdauletb/.local/share/virtualenvs/integration-tests-PN0lkqBU/lib/python3.6/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/home/bdauletb/.local/share/virtualenvs/integration-tests-PN0lkqBU/lib/python3.6/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/basic.py", line 102, in wait_for_adviser_to_finish
          exit_code = response.json()["status"]["exit_code"]
      KeyError: 'exit_code'
```

**Comment by bissenbay** [comment]
This issue is also related: https://github.com/thoth-station/thoth-application/issues/535

**Comment by bissenbay** [comment]
@goern @fridex When we schedule an integration test for thamos advise feature, should we only expect `200`, otherwise fail the test like it is correctly implemented? Or can we change the logic, so that having `404` error should pass the test as well?

**Comment by fridex** [comment]
> @goern @fridex When we schedule an integration test for thamos advise feature, should we only expect `200`, otherwise fail the test like it is correctly implemented? Or can we change the logic, so that having `404` error should pass the test as well?

404 is a bug on our side. The test should fail.

**Comment by bissenbay** [comment]
@fridex Can we close this issue?

**Comment by fridex** [comment]
> @fridex Can we close this issue?

Yes :+1:
