### ISSUE TITLE
integration test for solvers [5pt]

### ISSUE THREAD

**Issue by goern** [thoth-station/integration-tests#42]
As a Developer,
I want to run a solver feature test,
so that I can test if a specific package_version is resolved for all solvers configured

**Acceptance Criteria**
- [ ] documented which package is best for testing aka failing a lot (ask @fridex)
- [ ] think about opening github issues on failed test

**Comment by fridex** [comment]
Based on the discussion on the call, we miss this integration test. Not implemented yet.

**Comment by bissenbay** [comment]
@fridex What package do you think is failing a lot?

**Comment by fridex** [comment]
> @fridex What package do you think is failing a lot, is it `six`?

It would be good to query the database to have an answer to this. Not sure if we want to have most failing here though as solvers will not succeed in that case. You can pick one that is solvable, schedule solver analyses via management-api, mark solver id that is respobsible for solving the package, and then try to obtain solver results (again, from management-api).

**Comment by goern** [comment]
> > @fridex What package do you think is failing a lot, is it `six`?
> 
> It would be good to query the database to have an answer to this. Not sure if we want to have most failing here though as solvers will not succeed in that case. You can pick one that is solvable, schedule solver analyses via management-api, mark solver id that is respobsible for solving the package, and then try to obtain solver results (again, from management-api).

sounds like a good first step!

**Comment by goern** [comment]
what is the status with this?
