### ISSUE TITLE
Introduce integrations tests for investigator

### ISSUE THREAD

**Issue by pacospace** [thoth-station/integration-tests#52]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by goern** [comment]
@bissenbay any update on this?

**Comment by fridex** [comment]
I will close this one. The advise scenarios and package-extract scenarios involve investigator being up to serve user requests. Feel free to reopen if more testing or any more specific tests are needed.
