### ISSUE TITLE
checking db connection directly via integration test not the best approach

### ISSUE THREAD

**Issue by harshad16** [thoth-station/integration-tests#55]
**Describe the bug**
In the integration test, the feature to check the db connection is not the best approach.
https://github.com/thoth-station/integration-tests/blob/d47eda11daa3b68473fc376fc61ae2a60e3ee3d7/features/db_status.feature#L1

Directly trying to connect via storages, is not feasible. As we don't open our db connection outside the cluster, so integration tests running through CI which is deployed on a different cluster would not be able to make the connection.
https://github.com/thoth-station/integration-tests/blob/d47eda11daa3b68473fc376fc61ae2a60e3ee3d7/features/steps/db_status.py#L22

**To Reproduce**
1. Execute the integration test for production through a CI deployed on different clusters.
2. See error

**Expected behavior**
Integration test to fail due to error in the system, not because of the network issue.

**Screenshots**
![database-check](https://user-images.githubusercontent.com/14028058/95574630-ea518200-0a4a-11eb-8a00-85a57f02615d.png)

**Comment by goern** [comment]
we should exclude that feature via a tag?!

**Comment by harshad16** [comment]
> we should exclude that feature via a tag?!

yes, that should be good as we can have the db connection check enable for local tests. :+1:
